coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 0%
        informational: false
        paths:
          - "src"
      tools:
        target: 80%
        threshold: 0%
        informational: true
        paths:
          - "tools"
    patch:
      default:
        informational: true
