import { toComponentJsonSchemaVariableName, toKebabCaseFileStem } from "./naming.ts";
import type {
  OpenApiComponentSchema,
  OpenApiOperation,
  OpenApiRouteCatalog,
  JsonSchemaObject,
} from "./types.ts";

export const generatedHeader =
  "// This file is auto-generated by tools/generate-fastify-openapi.ts";
export const operationSections = ["params", "querystring", "headers", "body"] as const;

export type OperationSection = (typeof operationSections)[number];

export type EmittedZodSchema = {
  jsonSchemaConstName?: string;
  jsonSchemaLiteral?: string;
  schemaExpression: string;
};

export type ImportedComponentSchema = {
  componentFilePath: string;
  zodSchemaVariableName: string;
};

export type EmittedOperationResponseSchema = {
  schema?: EmittedZodSchema;
  schemaExpression: string;
  statusCode: string;
};

export type EmittedOperationSectionSchema = {
  schema: EmittedZodSchema;
  schemaExpression: string;
  schemaName: string;
  section: OperationSection;
};

function capitalize(value: string): string {
  return `${value.charAt(0).toUpperCase()}${value.slice(1)}`;
}

function renderJsonSchemaLiteral(schema: JsonSchemaObject): string {
  return JSON.stringify(schema, null, 2);
}

export function buildComponentJsonSchemaConstNamesByJsonSchema(
  openApiRouteCatalog: OpenApiRouteCatalog,
): Map<JsonSchemaObject, string> {
  const componentJsonSchemaConstNamesByJsonSchema = new Map<JsonSchemaObject, string>();

  for (const componentSchema of openApiRouteCatalog.componentSchemas) {
    componentJsonSchemaConstNamesByJsonSchema.set(
      componentSchema.schema,
      toComponentJsonSchemaVariableName(componentSchema.componentName),
    );
  }

  return componentJsonSchemaConstNamesByJsonSchema;
}

export function buildValueImportLine(
  importPath: string,
  valueImports: Iterable<string>,
): string | undefined {
  const importSpecifiers = Array.from(valueImports).toSorted();
  if (importSpecifiers.length === 0) {
    return undefined;
  }

  return `import { ${importSpecifiers.join(", ")} } from ${JSON.stringify(importPath)};`;
}

export function buildValueImportLinesByPath(
  valueImportsByPath: ReadonlyMap<string, ReadonlySet<string>>,
): string[] {
  return Array.from(valueImportsByPath.entries())
    .toSorted(([leftImportPath], [rightImportPath]) =>
      leftImportPath.localeCompare(rightImportPath),
    )
    .map(([importPath, valueImports]) => buildValueImportLine(importPath, valueImports))
    .filter((importLine) => importLine !== undefined);
}

export function getOperationFilePath(operation: OpenApiOperation): string {
  return `operations/${toKebabCaseFileStem(operation.operationId)}.ts`;
}

export function getComponentFilePath(componentSchema: OpenApiComponentSchema): string {
  return `components/${toKebabCaseFileStem(componentSchema.componentName)}.ts`;
}

export function getOperationJsonSchemaConstName(
  operation: OpenApiOperation,
  section: OperationSection,
): string {
  return `${operation.operationId}${capitalize(section)}JsonSchema`;
}

export function getOperationResponseJsonSchemaConstName(
  operation: OpenApiOperation,
  statusCode: string,
): string {
  return `${operation.operationId}${statusCode}ResponseJsonSchema`;
}

export function getOperationSectionSchemaName(
  operation: OpenApiOperation,
  section: OperationSection,
): string {
  return `${operation.operationId}${capitalize(section)}Schema`;
}

export function pushJsonSchemaConst(
  lines: string[],
  jsonSchemaConstName: string | undefined,
  jsonSchemaLiteral: string | undefined,
): void {
  if (jsonSchemaConstName === undefined || jsonSchemaLiteral === undefined) {
    return;
  }

  lines.push(`const ${jsonSchemaConstName} = ${jsonSchemaLiteral} as const;`);
  lines.push("");
}

export function renderEmittedZodSchema(
  jsonSchema: JsonSchemaObject,
  jsonSchemaConstName: string,
  openApiRouteCatalog: OpenApiRouteCatalog,
  importedComponentSchemas: ImportedComponentSchema[],
): EmittedZodSchema {
  const componentSchema = openApiRouteCatalog.componentSchemas.find(
    (candidateComponentSchema) => candidateComponentSchema.schema === jsonSchema,
  );
  if (componentSchema !== undefined) {
    importedComponentSchemas.push({
      componentFilePath: getComponentFilePath(componentSchema),
      zodSchemaVariableName: componentSchema.zodSchemaVariableName,
    });

    return {
      schemaExpression: componentSchema.zodSchemaVariableName,
    };
  }

  return {
    jsonSchemaConstName,
    jsonSchemaLiteral: renderJsonSchemaLiteral(jsonSchema),
    schemaExpression: `zodFromJsonSchemaTyped(${jsonSchemaConstName})`,
  };
}

export function renderInlineJsonSchemaLiteral(jsonSchema: JsonSchemaObject): string {
  return renderJsonSchemaLiteral(jsonSchema);
}
