import { toKebabCaseFileStem } from "./naming.ts";
import type {
  GeneratedFile,
  JsonSchema,
  NormalizedOperation,
  NormalizedResponseSchema,
} from "./types.ts";

export const generatedHeader =
  "// This file is auto-generated by tools/generate-fastify-openapi.ts";
export const operationSections = ["params", "querystring", "headers", "body"] as const;

export type OperationSection = (typeof operationSections)[number];

function assertUniqueGeneratedOperationFilePath(
  operationIdsByPath: Map<string, string>,
  relativePath: string,
  operationId: string,
): void {
  const existingOperationId = operationIdsByPath.get(relativePath);
  if (existingOperationId !== undefined && existingOperationId !== operationId) {
    throw new Error(
      `Generated file path collision: operation "${existingOperationId}" and operation "${operationId}" both map to "${relativePath}".`,
    );
  }

  operationIdsByPath.set(relativePath, operationId);
}

export function renderLiteral(value: JsonSchema | NormalizedResponseSchema): string {
  return JSON.stringify(value, null, 2);
}

export function getOperationFilePath(operation: NormalizedOperation): string {
  return `operations/${toKebabCaseFileStem(operation.operationId)}.ts`;
}

export function assertNoGeneratedOperationFilePathCollisions(
  operations: readonly NormalizedOperation[],
): void {
  const operationIdsByPath = new Map<string, string>();

  for (const operation of operations) {
    assertUniqueGeneratedOperationFilePath(
      operationIdsByPath,
      getOperationFilePath(operation),
      operation.operationId,
    );
  }
}

export function createGeneratedFile(
  relativePath: string,
  sections: ReadonlyArray<ReadonlyArray<string>>,
): GeneratedFile {
  return {
    content: `${sections.map((section) => section.join("\n")).join("\n\n")}\n`,
    relativePath,
  };
}
