import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import type { DefinePlugin, IR } from "@hey-api/openapi-ts";

import { collectResponseInfos } from "./responses.js";
import type { ResponseInfo } from "./responses.js";
import { fastifyPluginTypesTemplate } from "./templates.js";
import { collectRequiredZodSymbols } from "./zod-symbols.js";

type OperationInfo = {
  hasBody: boolean;
  hasHeaders: boolean;
  hasPath: boolean;
  hasQuery: boolean;
  id: string;
  method: string;
  path: string;
  responses: ResponseInfo[];
};

function toPascalCase(value: string): string {
  return value
    .replaceAll(/[^A-Za-z0-9]+/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function toFastifyPath(path: string): string {
  return path.replaceAll(/\{([^}]+)\}/g, ":$1");
}

function collectOperationInfo(operation: IR.OperationObject): OperationInfo {
  return {
    hasBody: Boolean(operation.body),
    hasHeaders: Boolean(
      operation.parameters?.header && Object.keys(operation.parameters.header).length > 0,
    ),
    hasPath: Boolean(
      operation.parameters?.path && Object.keys(operation.parameters.path).length > 0,
    ),
    hasQuery: Boolean(
      operation.parameters?.query && Object.keys(operation.parameters.query).length > 0,
    ),
    id: operation.id,
    method: operation.method.toUpperCase(),
    path: toFastifyPath(operation.path),
    responses: collectResponseInfos(operation),
  };
}

function generateImports(requiredZodSymbols: readonly string[]): string {
  const baseImports = [
    'import fastifyPlugin from "fastify-plugin";',
    'import type { FastifyPluginCallbackZod } from "fastify-type-provider-zod";',
    'import type { RouteHandlers } from "./fastify.gen.ts";',
  ];

  if (requiredZodSymbols.length === 0) {
    return baseImports.join("\n");
  }

  return [...baseImports, `import { ${requiredZodSymbols.join(", ")} } from "./zod.gen.ts";`].join(
    "\n",
  );
}

function generateSchemaProperties(operation: OperationInfo, indent: string): string[] {
  const lines: string[] = [];
  const operationName = toPascalCase(operation.id);
  const dataSymbol = `z${operationName}Data`;

  if (operation.hasPath) {
    lines.push(`${indent}params: ${dataSymbol}.shape.path,`);
  }

  if (operation.hasQuery) {
    lines.push(`${indent}querystring: ${dataSymbol}.shape.query,`);
  }

  if (operation.hasHeaders) {
    lines.push(`${indent}headers: ${dataSymbol}.shape.headers,`);
  }

  if (operation.hasBody) {
    lines.push(`${indent}body: ${dataSymbol}.shape.body,`);
  }

  if (operation.responses.length > 0) {
    const responses = operation.responses
      .map((response) => `"${response.status}": ${response.schemaSymbol}`)
      .join(", ");
    lines.push(`${indent}response: { ${responses} },`);
  } else {
    lines.push(`${indent}response: {},`);
  }

  return lines;
}

function generateRouteDefinition(operation: OperationInfo): string {
  const schemaProperties = generateSchemaProperties(operation, "      ");
  const operationIdLiteral = JSON.stringify(operation.id);

  return [
    `  ${operationIdLiteral}: {`,
    `    method: "${operation.method}",`,
    `    url: ${JSON.stringify(operation.path)},`,
    "    schema: {",
    ...schemaProperties,
    "    },",
    "  },",
  ].join("\n");
}

function generateRouteDefinitions(operations: readonly OperationInfo[]): string {
  return [
    "export const routeDefinitionsByOperationId = {",
    ...operations.map((operation) => generateRouteDefinition(operation)),
    "} as const;",
  ].join("\n");
}

function generateFastifyPlugin(operations: readonly OperationInfo[]): string {
  const statements = operations.map((operation) => {
    const operationIdLiteral = JSON.stringify(operation.id);
    return `  server.route({ ...routeDefinitionsByOperationId[${operationIdLiteral}], handler: handlers[${operationIdLiteral}] });`;
  });

  return [
    "const fastifyRoutesPluginImpl: FastifyPluginCallbackZod<FastifyRouteHandlersPluginOptions> = (",
    "  server,",
    "  options,",
    "  done,",
    "): void => {",
    "  const handlers = options.handlers;",
    "",
    ...statements,
    "",
    "  done();",
    "};",
    "",
    "export const fastifyRoutesPlugin = fastifyPlugin(fastifyRoutesPluginImpl, {",
    '  name: "fastify-routes",',
    "});",
  ].join("\n");
}

function generateFile(
  operations: readonly OperationInfo[],
  requiredZodSymbols: readonly string[],
): string {
  return [
    "// This file is auto-generated by the fastify-routes OpenAPI-TS plugin.",
    "// Do not edit manually.",
    "",
    generateImports(requiredZodSymbols),
    "",
    generateRouteDefinitions(operations),
    "",
    fastifyPluginTypesTemplate,
    "",
    generateFastifyPlugin(operations),
    "",
  ].join("\n");
}

export const fastifyRoutesPlugin: DefinePlugin["Config"] = {
  name: "fastify-routes",
  config: {
    includeInEntry: false,
  },
  dependencies: ["@hey-api/typescript", "fastify", "zod"],
  handler({ plugin }) {
    const operations: OperationInfo[] = [];

    // oxlint-disable-next-line unicorn/no-array-for-each -- OpenAPI-TS plugin API exposes this callback as "forEach".
    plugin.forEach(
      "operation",
      ({ operation }) => {
        operations.push(collectOperationInfo(operation));
      },
      { order: "declarations" },
    );

    mkdirSync(plugin.context.config.output.path, { recursive: true });

    const requiredZodSymbols = collectRequiredZodSymbols(operations);

    const outputPath = join(plugin.context.config.output.path, "fastify-routes.gen.ts");
    writeFileSync(outputPath, generateFile(operations, requiredZodSymbols), "utf8");
  },
};
