export const fastifyPluginTypesTemplate = [
  'type FastifyRouteOptionSubset = Pick<RouteShorthandOptionsWithHandler, "config" | "onRequest" | "preHandler" | "preValidation">;',
  "",
  "type FastifyRouteEntry<THandler extends RouteHandlers[keyof RouteHandlers]> =",
  "  | THandler",
  "  | (FastifyRouteOptionSubset & { handler: THandler });",
  "",
  "export type FastifyRouteEntries = {",
  "  [K in keyof RouteHandlers]: FastifyRouteEntry<RouteHandlers[K]>;",
  "};",
  "",
  "type FastifyRouteOptionsWithHandler<THandler extends RouteHandlers[keyof RouteHandlers]> =",
  "  FastifyRouteOptionSubset & { handler: THandler };",
  "",
  "function normalizeRouteEntry<THandler extends RouteHandlers[keyof RouteHandlers]>(",
  "  entry: FastifyRouteEntry<THandler>,",
  "): FastifyRouteOptionsWithHandler<THandler> {",
  '  if (typeof entry === "function") {',
  "    return { handler: entry };",
  "  }",
  "",
  "  return entry;",
  "}",
  "",
  "export type FastifyRoutesPluginOptions = { routes: FastifyRouteEntries };",
].join("\n");
