export const fastifyPluginTypesTemplate = [
  'type FastifyRouteOptions = Pick<RouteShorthandOptionsWithHandler, "config" | "onRequest" | "preHandler" | "preValidation">;',
  "",
  "type FastifyRouteHandlerOptions<THandler extends RouteHandlers[keyof RouteHandlers]> =",
  "  FastifyRouteOptions & { handler: THandler };",
  "",
  "type FastifyRouteHandlerInput<THandler extends RouteHandlers[keyof RouteHandlers]> =",
  "  | THandler",
  "  | FastifyRouteHandlerOptions<THandler>;",
  "",
  "export type FastifyRouteHandlers = {",
  "  [K in keyof RouteHandlers]: FastifyRouteHandlerInput<RouteHandlers[K]>;",
  "};",
  "",
  "function normalizeRouteHandler<THandler extends RouteHandlers[keyof RouteHandlers]>(",
  "  input: FastifyRouteHandlerInput<THandler>,",
  "): FastifyRouteHandlerOptions<THandler> {",
  '  if (typeof input === "function") {',
  "    return { handler: input };",
  "  }",
  "",
  "  return input;",
  "}",
  "",
  "export type FastifyRoutesPluginOptions = { routes: FastifyRouteHandlers };",
].join("\n");
