export const fastifyPluginTypesTemplate = [
  'type RouteHandlerHooks = Pick<RouteShorthandOptionsWithHandler, "config" | "onRequest" | "preHandler" | "preValidation">;',
  "",
  "type RouteHandlerRegistrationWithHandler<THandler extends RouteHandlers[keyof RouteHandlers]> =",
  "  RouteHandlerHooks & { handler: THandler };",
  "",
  "type RouteHandlerRegistration<THandler extends RouteHandlers[keyof RouteHandlers]> =",
  "  | THandler",
  "  | RouteHandlerRegistrationWithHandler<THandler>;",
  "",
  "export type RouteHandlerRegistrations = {",
  "  [K in keyof RouteHandlers]: RouteHandlerRegistration<RouteHandlers[K]>;",
  "};",
  "",
  "function normalizeRouteHandlerRegistration<THandler extends RouteHandlers[keyof RouteHandlers]>(",
  "  registration: RouteHandlerRegistration<THandler>,",
  "): RouteHandlerRegistrationWithHandler<THandler> {",
  '  if (typeof registration === "function") {',
  "    return { handler: registration };",
  "  }",
  "",
  "  return registration;",
  "}",
  "",
  "export type FastifyRoutesPluginOptions = { routes: RouteHandlerRegistrations };",
].join("\n");
