name: pgschema-apply
description: Install pgschema and apply a schema file to a Postgres database URL.

inputs:
  db-host:
    description: Postgres host.
    required: true
  db-port:
    description: Postgres port.
    required: false
    default: "5432"
  db-name:
    description: Postgres database name.
    required: true
  db-user:
    description: Postgres user.
    required: true
  db-password:
    description: Postgres password.
    required: true
  schema-file:
    description: Path to the schema SQL file.
    required: false
    default: db/schema.sql
  schema-name:
    description: Target Postgres schema name.
    required: false
    default: public
  pgschema-version:
    description: pgschema module version passed to go install.
    required: false
    default: latest

runs:
  using: composite
  steps:
    - name: Verify Go toolchain is available
      shell: bash
      run: |
        go version

    - name: Install pgschema
      shell: bash
      env:
        PGSCHEMA_VERSION: ${{ inputs.pgschema-version }}
      run: |
        if ! go install "github.com/pgplex/pgschema@${PGSCHEMA_VERSION}"; then
          go install "github.com/pgschema/pgschema@${PGSCHEMA_VERSION}"
        fi
        PGSCHEMA_BIN="$(go env GOPATH)/bin/pgschema"
        "${PGSCHEMA_BIN}" --help >/dev/null

    - name: Apply schema
      shell: bash
      env:
        PGHOST: ${{ inputs.db-host }}
        PGPORT: ${{ inputs.db-port }}
        PGDATABASE: ${{ inputs.db-name }}
        PGUSER: ${{ inputs.db-user }}
        PGPASSWORD: ${{ inputs.db-password }}
        SCHEMA_FILE: ${{ inputs.schema-file }}
        SCHEMA_NAME: ${{ inputs.schema-name }}
      run: |
        if [[ ! -f "${SCHEMA_FILE}" ]]; then
          echo "Schema file not found: ${SCHEMA_FILE}" >&2
          exit 1
        fi

        PGSCHEMA_BIN="$(go env GOPATH)/bin/pgschema"
        "${PGSCHEMA_BIN}" apply \
          --host "${PGHOST}" \
          --port "${PGPORT}" \
          --db "${PGDATABASE}" \
          --user "${PGUSER}" \
          --password "${PGPASSWORD}" \
          --schema "${SCHEMA_NAME}" \
          --file "${SCHEMA_FILE}" \
          --auto-approve
