// This file is auto-generated by the fastify-routes OpenAPI-TS plugin.
// Do not edit manually.

import fastifyPlugin from "fastify-plugin";
import type { FastifyPluginAsync, RouteShorthandOptionsWithHandler } from "fastify";
import type { RouteHandlers } from "./fastify.gen.ts";
import { zCreateGraphData, zCreateGraphResponse, zDeleteGraphData, zDeleteGraphResponse, zDeleteSubgraphData, zDeleteSubgraphResponse, zGetGraphData, zGetGraphResponse, zGetSubgraphData, zGetSubgraphResponse, zListGraphsResponse, zListSubgraphsData, zListSubgraphsResponse, zUpdateGraphData, zUpdateGraphResponse, zUpsertSubgraphData, zUpsertSubgraphResponse } from "./zod.gen.ts";

export const routePaths = {
  "listGraphs": "/v1/graphs",
  "createGraph": "/v1/graphs",
  "deleteGraph": "/v1/graphs/:graphSlug",
  "getGraph": "/v1/graphs/:graphSlug",
  "updateGraph": "/v1/graphs/:graphSlug",
  "listSubgraphs": "/v1/graphs/:graphSlug/subgraphs",
  "deleteSubgraph": "/v1/graphs/:graphSlug/subgraphs/:subgraphSlug",
  "getSubgraph": "/v1/graphs/:graphSlug/subgraphs/:subgraphSlug",
  "upsertSubgraph": "/v1/graphs/:graphSlug/subgraphs/:subgraphSlug",
} as const;

export const routeSchemas = {
  "listGraphs": {
    response: { 200: zListGraphsResponse },
  },
  "createGraph": {
    body: zCreateGraphData.shape.body,
    response: { 201: zCreateGraphResponse },
  },
  "deleteGraph": {
    params: zDeleteGraphData.shape.path,
    response: { 204: zDeleteGraphResponse },
  },
  "getGraph": {
    params: zGetGraphData.shape.path,
    response: { 200: zGetGraphResponse },
  },
  "updateGraph": {
    params: zUpdateGraphData.shape.path,
    headers: zUpdateGraphData.shape.headers,
    body: zUpdateGraphData.shape.body,
    response: { 200: zUpdateGraphResponse },
  },
  "listSubgraphs": {
    params: zListSubgraphsData.shape.path,
    response: { 200: zListSubgraphsResponse },
  },
  "deleteSubgraph": {
    params: zDeleteSubgraphData.shape.path,
    response: { 204: zDeleteSubgraphResponse },
  },
  "getSubgraph": {
    params: zGetSubgraphData.shape.path,
    response: { 200: zGetSubgraphResponse },
  },
  "upsertSubgraph": {
    params: zUpsertSubgraphData.shape.path,
    headers: zUpsertSubgraphData.shape.headers,
    body: zUpsertSubgraphData.shape.body,
    response: { 200: zUpsertSubgraphResponse, 201: zUpsertSubgraphResponse },
  },
} as const;

type FastifyRouteOptionSubset = Pick<RouteShorthandOptionsWithHandler, "config" | "onRequest" | "preHandler" | "preValidation">;

type FastifyRouteEntry<THandler extends RouteHandlers[keyof RouteHandlers]> =
  | THandler
  | (FastifyRouteOptionSubset & { handler: THandler });

export type FastifyRouteEntries = {
  [K in keyof RouteHandlers]: FastifyRouteEntry<RouteHandlers[K]>;
};

type FastifyRouteOptionsWithHandler<THandler extends RouteHandlers[keyof RouteHandlers]> =
  FastifyRouteOptionSubset & { handler: THandler };

function normalizeRouteEntry<THandler extends RouteHandlers[keyof RouteHandlers]>(
  entry: FastifyRouteEntry<THandler>,
): FastifyRouteOptionsWithHandler<THandler> {
  if (typeof entry === "function") {
    return { handler: entry };
  }

  return entry;
}

export type FastifyRoutesPluginOptions = { routes: FastifyRouteEntries };

const fastifyRoutesPluginImpl: FastifyPluginAsync<FastifyRoutesPluginOptions> = async (
  server,
  options,
): Promise<void> => {
  const routes = options.routes;

  server.get(routePaths["listGraphs"], { ...normalizeRouteEntry(routes["listGraphs"]), schema: routeSchemas["listGraphs"] });
  server.post(routePaths["createGraph"], { ...normalizeRouteEntry(routes["createGraph"]), schema: routeSchemas["createGraph"] });
  server.delete(routePaths["deleteGraph"], { ...normalizeRouteEntry(routes["deleteGraph"]), schema: routeSchemas["deleteGraph"] });
  server.get(routePaths["getGraph"], { ...normalizeRouteEntry(routes["getGraph"]), schema: routeSchemas["getGraph"] });
  server.put(routePaths["updateGraph"], { ...normalizeRouteEntry(routes["updateGraph"]), schema: routeSchemas["updateGraph"] });
  server.get(routePaths["listSubgraphs"], { ...normalizeRouteEntry(routes["listSubgraphs"]), schema: routeSchemas["listSubgraphs"] });
  server.delete(routePaths["deleteSubgraph"], { ...normalizeRouteEntry(routes["deleteSubgraph"]), schema: routeSchemas["deleteSubgraph"] });
  server.get(routePaths["getSubgraph"], { ...normalizeRouteEntry(routes["getSubgraph"]), schema: routeSchemas["getSubgraph"] });
  server.put(routePaths["upsertSubgraph"], { ...normalizeRouteEntry(routes["upsertSubgraph"]), schema: routeSchemas["upsertSubgraph"] });
};

export const fastifyRoutesPlugin = fastifyPlugin<FastifyRoutesPluginOptions>(
  fastifyRoutesPluginImpl,
  {
  name: "fastify-routes",
  },
);
