// This file is auto-generated by @hey-api/openapi-ts

import type { RouteHandler } from 'fastify';

import type { DeleteGraphData, DeleteGraphErrors, DeleteGraphResponses, DeleteSubgraphData, DeleteSubgraphErrors, DeleteSubgraphResponses, GetGraphData, GetGraphErrors, GetGraphResponses, GetSubgraphData, GetSubgraphErrors, GetSubgraphResponses, ListGraphsErrors, ListGraphsResponses, ListSubgraphsData, ListSubgraphsErrors, ListSubgraphsResponses, UpsertGraphData, UpsertGraphErrors, UpsertGraphResponses, UpsertSubgraphData, UpsertSubgraphErrors, UpsertSubgraphResponses } from './types.gen.js';

export type RouteHandlers = {
    listGraphs: RouteHandler<{
        Reply: ListGraphsErrors & ListGraphsResponses;
    }>;
    deleteGraph: RouteHandler<{
        Params: DeleteGraphData['path'];
        Reply: DeleteGraphErrors & DeleteGraphResponses;
    }>;
    getGraph: RouteHandler<{
        Params: GetGraphData['path'];
        Reply: GetGraphErrors & GetGraphResponses;
    }>;
    upsertGraph: RouteHandler<{
        Body: UpsertGraphData['body'];
        Headers: UpsertGraphData['headers'];
        Params: UpsertGraphData['path'];
        Reply: UpsertGraphErrors & UpsertGraphResponses;
    }>;
    listSubgraphs: RouteHandler<{
        Params: ListSubgraphsData['path'];
        Reply: ListSubgraphsErrors & ListSubgraphsResponses;
    }>;
    deleteSubgraph: RouteHandler<{
        Params: DeleteSubgraphData['path'];
        Reply: DeleteSubgraphErrors & DeleteSubgraphResponses;
    }>;
    getSubgraph: RouteHandler<{
        Params: GetSubgraphData['path'];
        Reply: GetSubgraphErrors & GetSubgraphResponses;
    }>;
    upsertSubgraph: RouteHandler<{
        Body: UpsertSubgraphData['body'];
        Headers: UpsertSubgraphData['headers'];
        Params: UpsertSubgraphData['path'];
        Reply: UpsertSubgraphErrors & UpsertSubgraphResponses;
    }>;
};
