// This file is auto-generated by the fastify-routes OpenAPI-TS plugin.
// Do not edit manually.

import fastifyPlugin from "fastify-plugin";
import type { FastifyPluginAsync, RouteShorthandOptionsWithHandler } from "fastify";
import type { RouteHandlers } from "./fastify.gen.ts";
import { zCreateGraphData, zCreateSubgraphData, zDeleteGraphData, zDeleteGraphResponse, zDeleteSubgraphData, zDeleteSubgraphResponse, zGetGraphData, zGetSubgraphData, zGraphListRoot, zGraphRoot, zListSubgraphsData, zRoot, zSubgraphListRoot, zSubgraphRoot, zUpdateGraphData, zUpdateSubgraphData } from "./zod.gen.ts";

export const routeDefinitions = {
  "listGraphs": {
    method: "GET",
    url: "/v1/graphs",
    schema: {
      response: { "200": zGraphListRoot, "401": zRoot, "403": zRoot },
    },
  },
  "createGraph": {
    method: "POST",
    url: "/v1/graphs",
    schema: {
      body: zCreateGraphData.shape.body,
      response: { "201": zGraphRoot, "401": zRoot, "403": zRoot, "409": zRoot },
    },
  },
  "deleteGraph": {
    method: "DELETE",
    url: "/v1/graphs/:graphSlug",
    schema: {
      params: zDeleteGraphData.shape.path,
      response: { "204": zDeleteGraphResponse, "401": zRoot, "403": zRoot },
    },
  },
  "getGraph": {
    method: "GET",
    url: "/v1/graphs/:graphSlug",
    schema: {
      params: zGetGraphData.shape.path,
      response: { "200": zGraphRoot, "401": zRoot, "403": zRoot, "404": zRoot },
    },
  },
  "updateGraph": {
    method: "PUT",
    url: "/v1/graphs/:graphSlug",
    schema: {
      params: zUpdateGraphData.shape.path,
      headers: zUpdateGraphData.shape.headers,
      body: zUpdateGraphData.shape.body,
      response: { "200": zGraphRoot, "400": zRoot, "401": zRoot, "403": zRoot, "404": zRoot, "409": zRoot },
    },
  },
  "listSubgraphs": {
    method: "GET",
    url: "/v1/graphs/:graphSlug/subgraphs",
    schema: {
      params: zListSubgraphsData.shape.path,
      response: { "200": zSubgraphListRoot, "401": zRoot, "403": zRoot, "404": zRoot },
    },
  },
  "createSubgraph": {
    method: "POST",
    url: "/v1/graphs/:graphSlug/subgraphs",
    schema: {
      params: zCreateSubgraphData.shape.path,
      body: zCreateSubgraphData.shape.body,
      response: { "201": zSubgraphRoot, "401": zRoot, "403": zRoot, "404": zRoot, "409": zRoot },
    },
  },
  "deleteSubgraph": {
    method: "DELETE",
    url: "/v1/graphs/:graphSlug/subgraphs/:subgraphSlug",
    schema: {
      params: zDeleteSubgraphData.shape.path,
      response: { "204": zDeleteSubgraphResponse, "401": zRoot, "403": zRoot },
    },
  },
  "getSubgraph": {
    method: "GET",
    url: "/v1/graphs/:graphSlug/subgraphs/:subgraphSlug",
    schema: {
      params: zGetSubgraphData.shape.path,
      response: { "200": zSubgraphRoot, "401": zRoot, "403": zRoot, "404": zRoot },
    },
  },
  "updateSubgraph": {
    method: "PUT",
    url: "/v1/graphs/:graphSlug/subgraphs/:subgraphSlug",
    schema: {
      params: zUpdateSubgraphData.shape.path,
      headers: zUpdateSubgraphData.shape.headers,
      body: zUpdateSubgraphData.shape.body,
      response: { "200": zSubgraphRoot, "400": zRoot, "401": zRoot, "403": zRoot, "404": zRoot, "409": zRoot },
    },
  },
} as const;

type FastifyRouteOptions = Pick<RouteShorthandOptionsWithHandler, "config" | "onRequest" | "preHandler" | "preValidation">;

type FastifyRouteHandlerOptions<THandler extends RouteHandlers[keyof RouteHandlers]> =
  FastifyRouteOptions & { handler: THandler };

type FastifyRouteHandlerInput<THandler extends RouteHandlers[keyof RouteHandlers]> =
  | THandler
  | FastifyRouteHandlerOptions<THandler>;

export type FastifyRouteHandlers = {
  [K in keyof RouteHandlers]: FastifyRouteHandlerInput<RouteHandlers[K]>;
};

function normalizeRouteHandler<THandler extends RouteHandlers[keyof RouteHandlers]>(
  input: FastifyRouteHandlerInput<THandler>,
): FastifyRouteHandlerOptions<THandler> {
  if (typeof input === "function") {
    return { handler: input };
  }

  return input;
}

export type FastifyRoutesPluginOptions = { routes: FastifyRouteHandlers };

const fastifyRoutesPluginImpl: FastifyPluginAsync<FastifyRoutesPluginOptions> = async (
  server,
  options,
): Promise<void> => {
  const routeHandlers = options.routes;

  server.route({ ...routeDefinitions["listGraphs"], ...normalizeRouteHandler(routeHandlers["listGraphs"]) });
  server.route({ ...routeDefinitions["createGraph"], ...normalizeRouteHandler(routeHandlers["createGraph"]) });
  server.route({ ...routeDefinitions["deleteGraph"], ...normalizeRouteHandler(routeHandlers["deleteGraph"]) });
  server.route({ ...routeDefinitions["getGraph"], ...normalizeRouteHandler(routeHandlers["getGraph"]) });
  server.route({ ...routeDefinitions["updateGraph"], ...normalizeRouteHandler(routeHandlers["updateGraph"]) });
  server.route({ ...routeDefinitions["listSubgraphs"], ...normalizeRouteHandler(routeHandlers["listSubgraphs"]) });
  server.route({ ...routeDefinitions["createSubgraph"], ...normalizeRouteHandler(routeHandlers["createSubgraph"]) });
  server.route({ ...routeDefinitions["deleteSubgraph"], ...normalizeRouteHandler(routeHandlers["deleteSubgraph"]) });
  server.route({ ...routeDefinitions["getSubgraph"], ...normalizeRouteHandler(routeHandlers["getSubgraph"]) });
  server.route({ ...routeDefinitions["updateSubgraph"], ...normalizeRouteHandler(routeHandlers["updateSubgraph"]) });
};

export const fastifyRoutesPlugin = fastifyPlugin<FastifyRoutesPluginOptions>(
  fastifyRoutesPluginImpl,
  {
  name: "fastify-routes",
  },
);
