// This file is auto-generated by @hey-api/openapi-ts

import type { RouteHandler } from 'fastify';

import type { CreateGraphData, CreateGraphErrors, CreateGraphResponses, CreateSubgraphData, CreateSubgraphErrors, CreateSubgraphResponses, DeleteGraphData, DeleteGraphErrors, DeleteGraphResponses, DeleteSubgraphData, DeleteSubgraphErrors, DeleteSubgraphResponses, GetGraphData, GetGraphErrors, GetGraphResponses, GetSubgraphData, GetSubgraphErrors, GetSubgraphResponses, ListGraphsErrors, ListGraphsResponses, ListSubgraphsData, ListSubgraphsErrors, ListSubgraphsResponses, UpdateGraphData, UpdateGraphErrors, UpdateGraphResponses, UpdateSubgraphData, UpdateSubgraphErrors, UpdateSubgraphResponses } from './types.gen.js';

export type RouteHandlers = {
    listGraphs: RouteHandler<{
        Reply: ListGraphsErrors & ListGraphsResponses;
    }>;
    createGraph: RouteHandler<{
        Body: CreateGraphData['body'];
        Reply: CreateGraphErrors & CreateGraphResponses;
    }>;
    deleteGraph: RouteHandler<{
        Params: DeleteGraphData['path'];
        Reply: DeleteGraphErrors & DeleteGraphResponses;
    }>;
    getGraph: RouteHandler<{
        Params: GetGraphData['path'];
        Reply: GetGraphErrors & GetGraphResponses;
    }>;
    updateGraph: RouteHandler<{
        Body: UpdateGraphData['body'];
        Headers: UpdateGraphData['headers'];
        Params: UpdateGraphData['path'];
        Reply: UpdateGraphErrors & UpdateGraphResponses;
    }>;
    listSubgraphs: RouteHandler<{
        Params: ListSubgraphsData['path'];
        Reply: ListSubgraphsErrors & ListSubgraphsResponses;
    }>;
    createSubgraph: RouteHandler<{
        Body: CreateSubgraphData['body'];
        Params: CreateSubgraphData['path'];
        Reply: CreateSubgraphErrors & CreateSubgraphResponses;
    }>;
    deleteSubgraph: RouteHandler<{
        Params: DeleteSubgraphData['path'];
        Reply: DeleteSubgraphErrors & DeleteSubgraphResponses;
    }>;
    getSubgraph: RouteHandler<{
        Params: GetSubgraphData['path'];
        Reply: GetSubgraphErrors & GetSubgraphResponses;
    }>;
    updateSubgraph: RouteHandler<{
        Body: UpdateSubgraphData['body'];
        Headers: UpdateSubgraphData['headers'];
        Params: UpdateSubgraphData['path'];
        Reply: UpdateSubgraphErrors & UpdateSubgraphResponses;
    }>;
};
