// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type Error = ErrorRoot;

export type FieldError = FieldErrorRoot;

export type Diagnostic = DiagnosticRoot;

export type Graph = GraphRoot;

export type GraphList = GraphListRoot;

export type CreateGraphRequest = CreateGraphRequestRoot;

export type UpdateGraphRequest = UpdateGraphRequestRoot;

export type Subgraph = SubgraphRoot;

export type SubgraphList = SubgraphListRoot;

export type UpsertSubgraphRequest = UpsertSubgraphRequestRoot;

export type Root = unknown;

export type SubgraphSlugRoot = unknown;

export type XRevisionIdRoot = unknown;

/**
 * Conflict
 */
export type ConflictRoot = unknown;

/**
 * Token lacks required scope
 */
export type ForbiddenRoot = unknown;

/**
 * Not found
 */
export type NotFoundRoot = unknown;

/**
 * Missing/invalid bearer token
 */
export type UnauthorizedRoot = unknown;

/**
 * Unprocessable entity
 */
export type UnprocessableEntityRoot = unknown;

export type CreateGraphRequestRoot = {
    graphSlug: string;
    federationVersion: string;
};

export type DiagnosticRoot = {
    level: 'info' | 'warning' | 'error';
    message: string;
    code?: string;
};

export type ErrorRoot = {
    type: string;
    title: string;
    status: number;
    detail?: string;
    instance?: string;
    code: 'UNAUTHORIZED' | 'FORBIDDEN' | 'NOT_FOUND' | 'CONFLICT' | 'INVALID_REQUEST' | 'INTERNAL_ERROR';
    requestId?: string;
    diagnostics?: Array<DiagnosticRoot>;
    errors?: Array<FieldErrorRoot>;
    upstreamCode?: string;
    [key: string]: unknown;
};

export type FieldErrorRoot = {
    path: string;
    message: string;
    rule?: string;
};

export type GraphListRoot = Array<GraphRoot>;

export type GraphRoot = {
    id: string;
    slug: string;
    revisionId: string;
    federationVersion: string;
    createdAt: string;
    updatedAt: string;
};

export type SubgraphListRoot = Array<SubgraphRoot>;

export type SubgraphRoot = {
    id: string;
    graphId: string;
    slug: string;
    revisionId: string;
    routingUrl: string;
    createdAt: string;
    updatedAt: string;
};

export type UpdateGraphRequestRoot = {
    federationVersion: string;
};

export type UpsertSubgraphRequestRoot = {
    routingUrl: string;
};

export type BearerAuthRoot = unknown;

export type GraphSlug = string;

export type SubgraphSlug = string;

export type XRevisionId = string;

export type ListGraphsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/graphs';
};

export type ListGraphsErrors = {
    /**
     * Missing/invalid bearer token
     */
    401: ErrorRoot;
    /**
     * Token lacks required scope
     */
    403: ErrorRoot;
};

export type ListGraphsError = ListGraphsErrors[keyof ListGraphsErrors];

export type ListGraphsResponses = {
    /**
     * OK
     */
    200: GraphListRoot;
};

export type ListGraphsResponse = ListGraphsResponses[keyof ListGraphsResponses];

export type CreateGraphData = {
    body: CreateGraphRequestRoot;
    path?: never;
    query?: never;
    url: '/v1/graphs';
};

export type CreateGraphErrors = {
    /**
     * Missing/invalid bearer token
     */
    401: ErrorRoot;
    /**
     * Token lacks required scope
     */
    403: ErrorRoot;
    /**
     * Conflict
     */
    409: ErrorRoot;
};

export type CreateGraphError = CreateGraphErrors[keyof CreateGraphErrors];

export type CreateGraphResponses = {
    /**
     * Created
     */
    201: GraphRoot;
};

export type CreateGraphResponse = CreateGraphResponses[keyof CreateGraphResponses];

export type DeleteGraphData = {
    body?: never;
    path: {
        graphSlug: string;
    };
    query?: never;
    url: '/v1/graphs/{graphSlug}';
};

export type DeleteGraphErrors = {
    /**
     * Missing/invalid bearer token
     */
    401: ErrorRoot;
    /**
     * Token lacks required scope
     */
    403: ErrorRoot;
};

export type DeleteGraphError = DeleteGraphErrors[keyof DeleteGraphErrors];

export type DeleteGraphResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteGraphResponse = DeleteGraphResponses[keyof DeleteGraphResponses];

export type GetGraphData = {
    body?: never;
    path: {
        graphSlug: string;
    };
    query?: never;
    url: '/v1/graphs/{graphSlug}';
};

export type GetGraphErrors = {
    /**
     * Missing/invalid bearer token
     */
    401: ErrorRoot;
    /**
     * Token lacks required scope
     */
    403: ErrorRoot;
    /**
     * Not found
     */
    404: ErrorRoot;
};

export type GetGraphError = GetGraphErrors[keyof GetGraphErrors];

export type GetGraphResponses = {
    /**
     * OK
     */
    200: GraphRoot;
};

export type GetGraphResponse = GetGraphResponses[keyof GetGraphResponses];

export type UpdateGraphData = {
    body: UpdateGraphRequestRoot;
    headers: {
        'x-revision-id': string;
    };
    path: {
        graphSlug: string;
    };
    query?: never;
    url: '/v1/graphs/{graphSlug}';
};

export type UpdateGraphErrors = {
    /**
     * Missing/invalid bearer token
     */
    401: ErrorRoot;
    /**
     * Token lacks required scope
     */
    403: ErrorRoot;
    /**
     * Conflict
     */
    409: ErrorRoot;
};

export type UpdateGraphError = UpdateGraphErrors[keyof UpdateGraphErrors];

export type UpdateGraphResponses = {
    /**
     * Updated
     */
    200: GraphRoot;
};

export type UpdateGraphResponse = UpdateGraphResponses[keyof UpdateGraphResponses];

export type ListSubgraphsData = {
    body?: never;
    path: {
        graphSlug: string;
    };
    query?: never;
    url: '/v1/graphs/{graphSlug}/subgraphs';
};

export type ListSubgraphsErrors = {
    /**
     * Missing/invalid bearer token
     */
    401: ErrorRoot;
    /**
     * Token lacks required scope
     */
    403: ErrorRoot;
    /**
     * Not found
     */
    404: ErrorRoot;
};

export type ListSubgraphsError = ListSubgraphsErrors[keyof ListSubgraphsErrors];

export type ListSubgraphsResponses = {
    /**
     * OK
     */
    200: SubgraphListRoot;
};

export type ListSubgraphsResponse = ListSubgraphsResponses[keyof ListSubgraphsResponses];

export type DeleteSubgraphData = {
    body?: never;
    path: {
        graphSlug: string;
        subgraphSlug: string;
    };
    query?: never;
    url: '/v1/graphs/{graphSlug}/subgraphs/{subgraphSlug}';
};

export type DeleteSubgraphErrors = {
    /**
     * Missing/invalid bearer token
     */
    401: ErrorRoot;
    /**
     * Token lacks required scope
     */
    403: ErrorRoot;
    /**
     * Not found
     */
    404: ErrorRoot;
};

export type DeleteSubgraphError = DeleteSubgraphErrors[keyof DeleteSubgraphErrors];

export type DeleteSubgraphResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteSubgraphResponse = DeleteSubgraphResponses[keyof DeleteSubgraphResponses];

export type GetSubgraphData = {
    body?: never;
    path: {
        graphSlug: string;
        subgraphSlug: string;
    };
    query?: never;
    url: '/v1/graphs/{graphSlug}/subgraphs/{subgraphSlug}';
};

export type GetSubgraphErrors = {
    /**
     * Missing/invalid bearer token
     */
    401: ErrorRoot;
    /**
     * Token lacks required scope
     */
    403: ErrorRoot;
    /**
     * Not found
     */
    404: ErrorRoot;
};

export type GetSubgraphError = GetSubgraphErrors[keyof GetSubgraphErrors];

export type GetSubgraphResponses = {
    /**
     * OK
     */
    200: SubgraphRoot;
};

export type GetSubgraphResponse = GetSubgraphResponses[keyof GetSubgraphResponses];

export type UpsertSubgraphData = {
    body: UpsertSubgraphRequestRoot;
    headers: {
        'x-revision-id': string;
    };
    path: {
        graphSlug: string;
        subgraphSlug: string;
    };
    query?: never;
    url: '/v1/graphs/{graphSlug}/subgraphs/{subgraphSlug}';
};

export type UpsertSubgraphErrors = {
    /**
     * Missing/invalid bearer token
     */
    401: ErrorRoot;
    /**
     * Token lacks required scope
     */
    403: ErrorRoot;
    /**
     * Not found
     */
    404: ErrorRoot;
    /**
     * Conflict
     */
    409: ErrorRoot;
    /**
     * Unprocessable entity
     */
    422: ErrorRoot;
};

export type UpsertSubgraphError = UpsertSubgraphErrors[keyof UpsertSubgraphErrors];

export type UpsertSubgraphResponses = {
    /**
     * Updated
     */
    200: SubgraphRoot;
    /**
     * Created
     */
    201: SubgraphRoot;
};

export type UpsertSubgraphResponse = UpsertSubgraphResponses[keyof UpsertSubgraphResponses];
