// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type Graph = GraphRoot;

export type GraphList = GraphListRoot;

export type CreateGraphRequest = CreateGraphRequestRoot;

export type UpdateGraphRequest = UpdateGraphRequestRoot;

export type Subgraph = SubgraphRoot;

export type SubgraphList = SubgraphListRoot;

export type CreateSubgraphRequest = CreateSubgraphRequestRoot;

export type UpdateSubgraphRequest = UpdateSubgraphRequestRoot;

export type Root = unknown;

export type SubgraphSlugRoot = unknown;

export type XRevisionIdRoot = unknown;

/**
 * Bad request
 */
export type BadRequestRoot = unknown;

/**
 * Conflict
 */
export type ConflictRoot = unknown;

/**
 * Forbidden
 */
export type ForbiddenRoot = unknown;

/**
 * Not found
 */
export type NotFoundRoot = unknown;

/**
 * Unauthorized
 */
export type UnauthorizedRoot = unknown;

/**
 * Unprocessable entity
 */
export type UnprocessableEntityRoot = unknown;

export type CreateGraphRequestRoot = {
    slug: string;
    federationVersion: string;
};

export type CreateSubgraphRequestRoot = {
    slug: string;
    routingUrl: string;
};

export type GraphListRoot = Array<GraphRoot>;

export type GraphRoot = {
    id: string;
    slug: string;
    revisionId: string;
    federationVersion: string;
    createdAt: string;
    updatedAt: string;
};

export type SubgraphListRoot = Array<SubgraphRoot>;

export type SubgraphRoot = {
    id: string;
    graphId: string;
    slug: string;
    revisionId: string;
    routingUrl: string;
    createdAt: string;
    updatedAt: string;
};

export type UpdateGraphRequestRoot = {
    federationVersion: string;
};

export type UpdateSubgraphRequestRoot = {
    routingUrl: string;
};

export type BearerAuthRoot = unknown;

export type GraphSlug = string;

export type SubgraphSlug = string;

export type XRevisionId = string;

export type ListGraphsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/graphs';
};

export type ListGraphsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type ListGraphsResponses = {
    /**
     * OK
     */
    200: GraphListRoot;
};

export type ListGraphsResponse = ListGraphsResponses[keyof ListGraphsResponses];

export type CreateGraphData = {
    body: CreateGraphRequestRoot;
    path?: never;
    query?: never;
    url: '/v1/graphs';
};

export type CreateGraphErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Conflict
     */
    409: unknown;
};

export type CreateGraphResponses = {
    /**
     * Created
     */
    201: GraphRoot;
};

export type CreateGraphResponse = CreateGraphResponses[keyof CreateGraphResponses];

export type DeleteGraphData = {
    body?: never;
    path: {
        graphSlug: string;
    };
    query?: never;
    url: '/v1/graphs/{graphSlug}';
};

export type DeleteGraphErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type DeleteGraphResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteGraphResponse = DeleteGraphResponses[keyof DeleteGraphResponses];

export type GetGraphData = {
    body?: never;
    path: {
        graphSlug: string;
    };
    query?: never;
    url: '/v1/graphs/{graphSlug}';
};

export type GetGraphErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not found
     */
    404: unknown;
};

export type GetGraphResponses = {
    /**
     * OK
     */
    200: GraphRoot;
};

export type GetGraphResponse = GetGraphResponses[keyof GetGraphResponses];

export type UpdateGraphData = {
    body: UpdateGraphRequestRoot;
    headers: {
        'x-revision-id': string;
    };
    path: {
        graphSlug: string;
    };
    query?: never;
    url: '/v1/graphs/{graphSlug}';
};

export type UpdateGraphErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: unknown;
};

export type UpdateGraphResponses = {
    /**
     * Updated
     */
    200: GraphRoot;
};

export type UpdateGraphResponse = UpdateGraphResponses[keyof UpdateGraphResponses];

export type ListSubgraphsData = {
    body?: never;
    path: {
        graphSlug: string;
    };
    query?: never;
    url: '/v1/graphs/{graphSlug}/subgraphs';
};

export type ListSubgraphsErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not found
     */
    404: unknown;
};

export type ListSubgraphsResponses = {
    /**
     * OK
     */
    200: SubgraphListRoot;
};

export type ListSubgraphsResponse = ListSubgraphsResponses[keyof ListSubgraphsResponses];

export type CreateSubgraphData = {
    body: CreateSubgraphRequestRoot;
    path: {
        graphSlug: string;
    };
    query?: never;
    url: '/v1/graphs/{graphSlug}/subgraphs';
};

export type CreateSubgraphErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: unknown;
};

export type CreateSubgraphResponses = {
    /**
     * Created
     */
    201: SubgraphRoot;
};

export type CreateSubgraphResponse = CreateSubgraphResponses[keyof CreateSubgraphResponses];

export type DeleteSubgraphData = {
    body?: never;
    path: {
        graphSlug: string;
        subgraphSlug: string;
    };
    query?: never;
    url: '/v1/graphs/{graphSlug}/subgraphs/{subgraphSlug}';
};

export type DeleteSubgraphErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
};

export type DeleteSubgraphResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteSubgraphResponse = DeleteSubgraphResponses[keyof DeleteSubgraphResponses];

export type GetSubgraphData = {
    body?: never;
    path: {
        graphSlug: string;
        subgraphSlug: string;
    };
    query?: never;
    url: '/v1/graphs/{graphSlug}/subgraphs/{subgraphSlug}';
};

export type GetSubgraphErrors = {
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not found
     */
    404: unknown;
};

export type GetSubgraphResponses = {
    /**
     * OK
     */
    200: SubgraphRoot;
};

export type GetSubgraphResponse = GetSubgraphResponses[keyof GetSubgraphResponses];

export type UpdateSubgraphData = {
    body: UpdateSubgraphRequestRoot;
    headers: {
        'x-revision-id': string;
    };
    path: {
        graphSlug: string;
        subgraphSlug: string;
    };
    query?: never;
    url: '/v1/graphs/{graphSlug}/subgraphs/{subgraphSlug}';
};

export type UpdateSubgraphErrors = {
    /**
     * Bad request
     */
    400: unknown;
    /**
     * Unauthorized
     */
    401: unknown;
    /**
     * Forbidden
     */
    403: unknown;
    /**
     * Not found
     */
    404: unknown;
    /**
     * Conflict
     */
    409: unknown;
};

export type UpdateSubgraphResponses = {
    /**
     * Updated
     */
    200: SubgraphRoot;
};

export type UpdateSubgraphResponse = UpdateSubgraphResponses[keyof UpdateSubgraphResponses];
