// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zRoot = z.unknown();

export const zSubgraphSlugRoot = z.unknown();

export const zXRevisionIdRoot = z.unknown();

/**
 * Bad request
 */
export const zBadRequestRoot = z.unknown();

/**
 * Conflict
 */
export const zConflictRoot = z.unknown();

/**
 * Token lacks required scope
 */
export const zForbiddenRoot = z.unknown();

/**
 * Not found
 */
export const zNotFoundRoot = z.unknown();

/**
 * Missing/invalid bearer token
 */
export const zUnauthorizedRoot = z.unknown();

/**
 * Unprocessable entity
 */
export const zUnprocessableEntityRoot = z.unknown();

export const zCreateGraphRequestRoot = z.object({
    slug: z.string().min(1),
    federationVersion: z.string().min(1)
});

export const zCreateGraphRequest = zCreateGraphRequestRoot;

export const zCreateSubgraphRequestRoot = z.object({
    slug: z.string(),
    routingUrl: z.url()
});

export const zCreateSubgraphRequest = zCreateSubgraphRequestRoot;

export const zGraphRoot = z.object({
    id: z.uuid(),
    slug: z.string(),
    revisionId: z.string().regex(/^[1-9][0-9]*$/),
    federationVersion: z.string(),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime()
});

export const zGraph = zGraphRoot;

export const zGraphListRoot = z.array(zGraphRoot);

export const zGraphList = zGraphListRoot;

export const zSubgraphRoot = z.object({
    id: z.uuid(),
    graphId: z.uuid(),
    slug: z.string(),
    revisionId: z.string().regex(/^[1-9][0-9]*$/),
    routingUrl: z.url(),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime()
});

export const zSubgraph = zSubgraphRoot;

export const zSubgraphListRoot = z.array(zSubgraphRoot);

export const zSubgraphList = zSubgraphListRoot;

export const zUpdateGraphRequestRoot = z.object({
    federationVersion: z.string().min(1)
});

export const zUpdateGraphRequest = zUpdateGraphRequestRoot;

export const zUpdateSubgraphRequestRoot = z.object({
    routingUrl: z.url()
});

export const zUpdateSubgraphRequest = zUpdateSubgraphRequestRoot;

export const zBearerAuthRoot = z.unknown();

export const zGraphSlug = z.string().min(1);

export const zSubgraphSlug = z.string().min(1);

export const zXRevisionId = z.string().regex(/^[1-9][0-9]*$/);

export const zListGraphsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zListGraphsResponse = zGraphListRoot;

export const zCreateGraphData = z.object({
    body: zCreateGraphRequestRoot,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Created
 */
export const zCreateGraphResponse = zGraphRoot;

export const zDeleteGraphData = z.object({
    body: z.never().optional(),
    path: z.object({
        graphSlug: z.string().min(1)
    }),
    query: z.never().optional()
});

/**
 * No Content
 */
export const zDeleteGraphResponse = z.void();

export const zGetGraphData = z.object({
    body: z.never().optional(),
    path: z.object({
        graphSlug: z.string().min(1)
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetGraphResponse = zGraphRoot;

export const zUpdateGraphData = z.object({
    body: zUpdateGraphRequestRoot,
    path: z.object({
        graphSlug: z.string().min(1)
    }),
    query: z.never().optional(),
    headers: z.object({
        'x-revision-id': z.string().regex(/^[1-9][0-9]*$/)
    })
});

/**
 * Updated
 */
export const zUpdateGraphResponse = zGraphRoot;

export const zListSubgraphsData = z.object({
    body: z.never().optional(),
    path: z.object({
        graphSlug: z.string().min(1)
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zListSubgraphsResponse = zSubgraphListRoot;

export const zCreateSubgraphData = z.object({
    body: zCreateSubgraphRequestRoot,
    path: z.object({
        graphSlug: z.string().min(1)
    }),
    query: z.never().optional()
});

/**
 * Created
 */
export const zCreateSubgraphResponse = zSubgraphRoot;

export const zDeleteSubgraphData = z.object({
    body: z.never().optional(),
    path: z.object({
        graphSlug: z.string().min(1),
        subgraphSlug: z.string().min(1)
    }),
    query: z.never().optional()
});

/**
 * No Content
 */
export const zDeleteSubgraphResponse = z.void();

export const zGetSubgraphData = z.object({
    body: z.never().optional(),
    path: z.object({
        graphSlug: z.string().min(1),
        subgraphSlug: z.string().min(1)
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetSubgraphResponse = zSubgraphRoot;

export const zUpdateSubgraphData = z.object({
    body: zUpdateSubgraphRequestRoot,
    path: z.object({
        graphSlug: z.string().min(1),
        subgraphSlug: z.string().min(1)
    }),
    query: z.never().optional(),
    headers: z.object({
        'x-revision-id': z.string().regex(/^[1-9][0-9]*$/)
    })
});

/**
 * Updated
 */
export const zUpdateSubgraphResponse = zSubgraphRoot;
