-- GRANT ALL ON SCHEMA public TO cloud_admin;

CREATE ROLE cloud_admin WITH SUPERUSER;

CREATE ROLE neon_superuser WITH NOLOGIN IN ROLE cloud_admin NOINHERIT;

ALTER DEFAULT PRIVILEGES FOR ROLE cloud_admin IN SCHEMA public GRANT SELECT, UPDATE, USAGE ON SEQUENCES TO neon_superuser WITH GRANT OPTION;

ALTER DEFAULT PRIVILEGES FOR ROLE cloud_admin IN SCHEMA public GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLES TO neon_superuser WITH GRANT OPTION;

\i schema.sql

-- GRANT ALL ON SCHEMA public TO neon_superuser;

GRANT ALL ON ALL TABLES IN SCHEMA public TO neon_superuser;
