name: drizzle-schema

on:
  workflow_call:

permissions:
  contents: read

jobs:
  drizzle-schema:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          run_install: false

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: node --run drizzle:schema:generate
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

      - run: git --no-pager diff --no-color --exit-code
