name: test

on:
  workflow_call:

permissions:
  contents: read

jobs:
  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5
        with:
          run_install: false

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: node --run test:unit:coverage

      - uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        if: ${{ always() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.unit.info
          flags: unit

  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5
        with:
          run_install: false

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: psql -h localhost -p 5432 -U postgres -d postgres -v ON_ERROR_STOP=1 -f db/schema-extensions.sql
        env:
          PGPASSWORD: postgres

      - uses: ./.github/actions/pgschema-apply
        env:
          PGHOST: localhost
          PGPORT: "5432"
          PGDATABASE: postgres
          PGUSER: postgres
          PGPASSWORD: postgres
        with:
          pgschema-package-version: v1.9.0
          pgschema-package: github.com/pgplex/pgschema
          file: db/local.sql

      - run: node --run test:integration:coverage
        env:
          INTEGRATION_TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

      - uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        if: ${{ always() }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.integration.info
          flags: integration
