name: pnpm-up

on:
  schedule:
    - cron: "15 9 * * *"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: cysp/cyspbot-action@d879d41c65cc2cc85387bc0f483f33f97d9001ae # v0.0.1
        id: cyspbot

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          run_install: false

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - run: pnpm up -r

      - run: pnpm dedupe

      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.cyspbot.outputs.token }}
          commit-message: "chore(deps): bump transitive dependencies"
          title: "chore(deps): bump transitive dependencies"
          body: ""
          branch: "deps/pnpm-up"
          sign-commits: true
